package com.briup.apps.poll.bean;
/**
 * POJO类    问卷-问题(桥表)
 * @author WE
 *
 */
public class QuestionnaireQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_questionnaire_question.id
     *
     * @mbg.generated Mon Jun 25 17:09:53 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_questionnaire_question.questionnaire_id
     *
     * @mbg.generated Mon Jun 25 17:09:53 CST 2018
     */
    private Long questionnaireId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_questionnaire_question.question_id
     *
     * @mbg.generated Mon Jun 25 17:09:53 CST 2018
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_questionnaire_question.id
     *
     * @return the value of poll_questionnaire_question.id
     *
     * @mbg.generated Mon Jun 25 17:09:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_questionnaire_question.id
     *
     * @param id the value for poll_questionnaire_question.id
     *
     * @mbg.generated Mon Jun 25 17:09:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_questionnaire_question.questionnaire_id
     *
     * @return the value of poll_questionnaire_question.questionnaire_id
     *
     * @mbg.generated Mon Jun 25 17:09:53 CST 2018
     */
    public Long getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_questionnaire_question.questionnaire_id
     *
     * @param questionnaireId the value for poll_questionnaire_question.questionnaire_id
     *
     * @mbg.generated Mon Jun 25 17:09:53 CST 2018
     */
    public void setQuestionnaireId(Long questionnaireId) {
        this.questionnaireId = questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_questionnaire_question.question_id
     *
     * @return the value of poll_questionnaire_question.question_id
     *
     * @mbg.generated Mon Jun 25 17:09:53 CST 2018
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_questionnaire_question.question_id
     *
     * @param questionId the value for poll_questionnaire_question.question_id
     *
     * @mbg.generated Mon Jun 25 17:09:53 CST 2018
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}