package com.briup.apps.poll.dao;

import com.briup.apps.poll.bean.Survy;
import com.briup.apps.poll.bean.SurvyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SurvyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    long countByExample(SurvyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    int deleteByExample(SurvyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    int insert(Survy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    int insertSelective(Survy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    List<Survy> selectByExample(SurvyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    Survy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Survy record, @Param("example") SurvyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    int updateByExample(@Param("record") Survy record, @Param("example") SurvyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    int updateByPrimaryKeySelective(Survy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poll_survey
     *
     * @mbg.generated Mon Jun 25 17:09:52 CST 2018
     */
    int updateByPrimaryKey(Survy record);
}